# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nn-LGexwcvaeEsI08hFLsIgXVpH2LPO5
"""

import streamlit as st
import pandas as pd
import numpy as np

# Set page config
st.set_page_config(page_title="Prescriptive Churn Analytics", layout="wide")

# Load Data
@st.cache_data
def load_data():
    return pd.read_csv('final_dashboard_data.csv')

df = load_data()

# --- SIDEBAR (Filters) ---
st.sidebar.header("Filter Customer Base")
selected_country = st.sidebar.multiselect("Select Country", options=df['Country'].unique(), default=df['Country'].unique())
min_ltv = st.sidebar.slider("Minimum Lifetime Value ($)", min_value=float(df['Lifetime_Value'].min()), max_value=float(df['Lifetime_Value'].max()), value=0.0)

# Apply filters
filtered_df = df[(df['Country'].isin(selected_country)) & (df['Lifetime_Value'] >= min_ltv)]

# --- MAIN DASHBOARD ---
st.title("Enterprise Churn Management & Profit Optimization")
st.markdown("This dashboard translates predictive churn probabilities into prescriptive financial actions.")

# Top-level KPIs
col1, col2, col3 = st.columns(3)

total_customers = len(filtered_df)
high_risk_customers = len(filtered_df[filtered_df['Prescriptive_Action'] == 'Trigger Retention Campaign (15% Discount)'])
ltv_at_risk = filtered_df[filtered_df['Prescriptive_Action'] == 'Trigger Retention Campaign (15% Discount)']['Lifetime_Value'].sum()

col1.metric("Total Customers in View", f"{total_customers:,}")
col2.metric("High-Value Customers Requiring Intervention", f"{high_risk_customers:,}")
col3.metric("Total Revenue at Risk", f"${ltv_at_risk:,.2f}")

st.divider()

# Actionable Customer Table
st.subheader("Targeted Intervention List")
st.markdown("These customers cross the optimal profit threshold. Deploy the recommended action immediately.")

# Format the dataframe for display
display_df = filtered_df.copy()
display_df['Predicted_Prob'] = (display_df['Predicted_Prob'] * 100).round(1).astype(str) + '%'
display_df['Lifetime_Value'] = '$' + display_df['Lifetime_Value'].round(2).astype(str)

# Show only actionable customers sorted by LTV (highest value first)
action_df = display_df[display_df['Prescriptive_Action'] != 'Do Not Intervene'].sort_values(by='Lifetime_Value', ascending=False)
st.dataframe(action_df[['Country', 'City', 'Membership_Years', 'Lifetime_Value', 'Predicted_Prob', 'Prescriptive_Action']], use_container_width=True)